# app/services/cleaner.py
from pathlib import Path
from llama_index.llms.ollama import Ollama

class TextCleaner:
    def __init__(self):
        # 整形には時間がかかるので、タイムアウトを長め(10分)にとる
        self.llm = Ollama(
            model="qwen2.5:14b", 
            request_timeout=600.0,
            temperature=0.1 # 創造性は不要。忠実に直させる。
        )

    def clean_markdown_file(self, md_path: str) -> str:
        """
        Markdownファイルを読み込み、フォーマット（コードブロック、表、インデント）を
        LLMを使って修復し、上書き保存する。
        """
        path = Path(md_path)
        if not path.exists():
            print(f"Cleaner: File not found {md_path}")
            return md_path

        print(f"Cleaner: Fixing formatting for {path.name}...")

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        # ファイルが長すぎるとLLMが扱えないので、「## 」(大見出し)で分割して処理する
        sections = content.split("\n## ")
        
        cleaned_sections = []
        total_sections = len(sections)

        for i, section in enumerate(sections):
            # 最初の分割で空文字が出ることがあるのでスキップ
            if not section.strip():
                continue
            
            # 見出し記号がsplitで消えているので戻す（最初のセクション以外）
            header_prefix = "## " if i > 0 or content.startswith("## ") else ""
            raw_text = header_prefix + section

            print(f"  - Cleaning section {i+1}/{total_sections} ({len(raw_text)} chars)...")
            
            # LLMに投げる
            cleaned_text = self._fix_text_with_llm(raw_text)
            cleaned_sections.append(cleaned_text)

        # 結合して保存
        full_cleaned_text = "\n\n".join(cleaned_sections)
        
        # バックアップをとっておく（念のため）
        backup_path = path.with_suffix(".md.bak")
        with open(backup_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        # 上書き保存
        with open(path, "w", encoding="utf-8") as f:
            f.write(full_cleaned_text)

        print(f"Cleaner: Done! Backup saved at {backup_path.name}")
        return str(path)

    def _fix_text_with_llm(self, text: str) -> str:
        """
        テキストの断片を受け取り、フォーマットを修正させる
        """
        prompt = (
            "You are a strictly accurate document formatter. "
            "The following Markdown text was generated by OCR and has formatting issues.\n"
            "Please fix the following problems ONLY, without changing the wording or content:\n"
            "1. Restore indentation for programming code (C, Python, etc.).\n"
            "2. Fix broken Markdown tables (restore | separators and alignment).\n"
            "3. Fix fragmented mathematical formulas.\n\n"
            "IMPORTANT: Output only the corrected Markdown text. Do not add any conversational text.\n\n"
            "--- TEXT START ---\n"
            f"{text}\n"
            "--- TEXT END ---"
        )

        try:
            response = self.llm.complete(prompt)
            return response.text.strip()
        except Exception as e:
            print(f"  [Warning] LLM cleaning failed for this section: {e}")
            # 失敗したら元のテキストをそのまま返す（データ消失を防ぐ）
            return text
